### ISSUE TITLE
Memory Leak in Aplite

### ISSUE THREAD

**Issue by getmethere** [smallstoneapps/sliding-text-layer#1]
There is a small memory leak during the animation process in Aplite

**Comment by getmethere** [comment]
I found out that in Aplite you still need to destroy animations.  Therefore simply adding:
#ifdef PBL_PLATFORM_APLITE
    // Free the animation
    animation_destroy(anim);
  #endif
at the end of animation_stopped() fixes the problem!

**Comment by matthewtole** [comment]
Fixed in c17dcb5c444960e1b942c0a157b9014b574c2fc3
